# Site settings
title: Shang-Hung Shih
description:
  en: "Shang-Hung Shih has worked as a software engineer at the genomics team in Taiwan AILabs for two years. Prior to this, He graduated from National Taiwan University (NTU) and Academia Sinica with master degree in Bioinformatics, and worked with Prof. Chien-Yu Chen."
  en: "The style of this website is borrowed from Hexiang(Frank) Hu's."
  cn: "這是施尚宏的個人網頁，用於分享他的個人經歷、專案。"
keywords:
  en: "Shang-Hung Shih,Software Engineer,Web Development,Machine Learning,Bioinformatics,Next Generation Sequencing"
  cn: "施尚宏,軟體工程,網頁開發,機器學習,生物資訊,次世代定序"
background: /images/background/background-cube.jpg
deep_background: /images/background/background-deepcube-2.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://shanghungshih.github.io"
# the base hostname & protocol for your sit

# Paginationœ
paginate: 6
paginate_path: "/nono/posts/page/:num/"

# Build settings
markdown: kramdown

# permalink setting
permalink: pretty
# highlighter: rouge
highlighter: rouge

# Social media link for the site
social:
  # twitter:    adgh456
  github:     shanghungshih
  facebook:   shanghungshih
  linkedin:   shanghungshih
  # rss:        /feed.xml

google_analytics_token: "UA-60071442-1"
google_tags_token: "GTM-K5ZTMW"


# customized document resources
collections:
  projects:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

gems:
  ['jekyll-paginate', 'jekyll/scholar', 'jekyll-sitemap']
